// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
       return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

//Datos de conexion con la base de datos en FIREBASE(Datos modificados a nueva base)
  static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyBcee6o50iCy4biNsixCtXY7NN3djPXhfU',
  appId: '1:197222537051:android:20d4e85cb48a34a3d12c7e',
  messagingSenderId: '197222537051',
  projectId: 'pricetest-733fa',
  storageBucket: 'pricetest-733fa.firebasestorage.app',
);

//Modificado
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDopW2HiQc2seb13Y-TG8ZQJO9aQTIx2cg',
    appId: '1:197222537051:web:a56d71638cf6e451d12c7e',
    messagingSenderId: '197222537051',
    projectId: 'pricetest-733fa',
    authDomain: 'pricetest-733fa.firebaseapp.com',
    storageBucket: 'pricetest-733fa.firebasestorage.app',
    measurementId: 'G-FP0DGJM55G',
  );

//Modificado
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTnUz4_vooLkGnp2s7EBBMUngjsWtX7-4',
    appId: '1:197222537051:ios:d7038734bb91721cd12c7e',
    messagingSenderId: '197222537051',
    projectId: 'pricetest-733fa',
    storageBucket: 'pricetest-733fa.firebasestorage.app',
    iosBundleId: 'com.SynergyLabs.gatedcommunity',
  );

//Modificado
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTnUz4_vooLkGnp2s7EBBMUngjsWtX7-4',
    appId: '1:197222537051:ios:d7038734bb91721cd12c7e',
    messagingSenderId: '197222537051',
    projectId: 'pricetest-733fa',
    storageBucket: 'pricetest-733fa.firebasestorage.app',
    iosBundleId: 'com.SynergyLabs.gatedcommunity',
  );

//Modificado
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDopW2HiQc2seb13Y-TG8ZQJO9aQTIx2cg',
    appId: '1:197222537051:web:a56d71638cf6e451d12c7e',
    messagingSenderId: '197222537051',
    projectId: 'pricetest-733fa',
    authDomain: 'pricetest-733fa.firebaseapp.com',
    storageBucket: 'pricetest-733fa.firebasestorage.app',
    measurementId: 'G-FP0DGJM55G',
  );
}
